import { useState } from 'react'
import { CalendarDays, Check, ChevronRight, Clock3, Download, FileText, Filter, Search, UserRound, Users, X, TrendingUp, Send } from 'lucide-react'

// Shared UI for the Teacher and Parent portals. Local data is intentionally kept
// separate from the presentation so API services can replace it later.
const students=[['ST-1001','Ahmed Khan','Present','08:02 AM'],['ST-1002','Sara Ali','Present','08:07 AM'],['ST-1003','Hamza Raza','Absent','—'],['ST-1004','Maham Noor','Late','08:21 AM'],['ST-1005','Usman Tariq','Present','08:04 AM'],['ST-1006','Hira Shah','Present','08:09 AM']]
const history=[['Aug 17, 2026','32','30','1','1','94%'],['Aug 14, 2026','32','29','2','1','91%'],['Aug 13, 2026','32','31','0','1','97%'],['Aug 12, 2026','32','28','3','1','88%'],['Aug 11, 2026','32','30','2','0','94%']]
const leaves=[['LR-1042','Sara Ali','Sick Leave','Aug 18 – Aug 19','Pending'],['LR-1041','Hamza Raza','Family Event','Aug 20','Pending'],['LR-1040','Maham Noor','Medical Leave','Aug 17 – Aug 18','Approved']]

export default function PortalModule({type}){
  const pages={teacherDashboard:<TeacherDashboard/>,class:<MyClass/>,monitoring:<AttendanceMonitoring/>,history:<AttendanceHistory/>,teacherLeaves:<TeacherLeaves/>,parentDashboard:<ParentDashboard/>,parentAttendance:<ParentAttendance/>,applyLeave:<ApplyLeave/>,leaveHistory:<LeaveHistory/>}
  return pages[type]||null
}
function TeacherDashboard(){return <Shell title="Teacher Dashboard" description="Good morning, Ayesha. Here is your class overview for today."><Stats items={[["Students","32",Users],["Present","29",Check],["Late","2",Clock3],["Attendance","91%",TrendingUp]]}/><div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><Panel title="Today’s attendance" action="View monitoring"><AttendanceTable rows={students.slice(0,5)}/></Panel><Panel title="Quick actions"><div className="space-y-3"><QuickAction icon={Check} title="Take attendance" text="Mark today’s class attendance"/><QuickAction icon={FileText} title="Review leave requests" text="2 requests need attention"/><QuickAction icon={Download} title="Attendance report" text="Download class summary"/></div></Panel></div></Shell>}
function MyClass(){const [query,setQuery]=useState('');const filtered=students.filter(s=>`${s[0]} ${s[1]}`.toLowerCase().includes(query.toLowerCase()));return <Shell title="My Class" description="Class 10-A · Mathematics · 32 students"><Panel><div className="flex flex-col gap-4 border-b border-slate-100 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold">Student roster</h3><p className="text-xs text-slate-400">Manage students assigned to your class.</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2"><Search size={17} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students..." className="w-52 bg-transparent text-sm outline-none"/></div></div><div className="mt-5"><AttendanceTable rows={filtered}/></div></Panel></Shell>}
function AttendanceMonitoring(){const [rows,setRows]=useState(students);const setStatus=(id,status)=>setRows(r=>r.map(s=>s[0]===id?[s[0],s[1],status,status==='Absent'?'—':status==='Late'?'08:20 AM':'08:05 AM']:s));return <Shell title="Attendance Monitoring" description="Record today’s attendance for Class 10-A."><Panel><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold">Monday, August 17</h3><p className="text-xs text-slate-400">Mark each student as present, late or absent.</p></div><button className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Save attendance</button></div><div className="space-y-3">{rows.map(s=><div key={s[0]} className="flex flex-col gap-3 rounded-xl border border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-indigo-50 text-indigo-600"><UserRound size={18}/></div><div><p className="font-semibold">{s[1]}</p><p className="text-xs text-slate-400">{s[0]} · {s[3]}</p></div></div><div className="flex gap-2"><StatusButton active={s[2]==='Present'} onClick={()=>setStatus(s[0],'Present')} text="Present" type="present"/><StatusButton active={s[2]==='Late'} onClick={()=>setStatus(s[0],'Late')} text="Late" type="late"/><StatusButton active={s[2]==='Absent'} onClick={()=>setStatus(s[0],'Absent')} text="Absent" type="absent"/></div></div>)}</div></Panel></Shell>}
function AttendanceHistory(){return <Shell title="Attendance History" description="Review attendance records for your assigned class."><Panel><div className="mb-5 flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><CalendarDays size={16}/> Aug 1 – Aug 17, 2026</button><button className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><Filter size={16}/> Class 10-A</button><button className="ml-auto inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-3 py-2 text-sm font-semibold text-white"><Download size={16}/> Export</button></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{['Date','Students','Present','Absent','Late','Rate'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{history.map(r=><tr key={r[0]}><td className="px-4 py-4 font-semibold">{r[0]}</td><td className="px-4 py-4 text-slate-500">{r[1]}</td><td className="px-4 py-4 text-emerald-600">{r[2]}</td><td className="px-4 py-4 text-rose-500">{r[3]}</td><td className="px-4 py-4 text-amber-600">{r[4]}</td><td className="px-4 py-4 font-bold">{r[5]}</td></tr>)}</tbody></table></div></Panel></Shell>}
function TeacherLeaves(){const [items,setItems]=useState(leaves);const update=(id,status)=>setItems(x=>x.map(r=>r[0]===id?[...r.slice(0,4),status]:r));return <Shell title="Leave Requests" description="Review applications submitted by your students."><Panel><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">Pending applications</h3><p className="text-xs text-slate-400">Approve or reject requests after reviewing details.</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">{items.filter(x=>x[4]==='Pending').length} pending</span></div><div className="space-y-3">{items.map(r=><div key={r[0]} className="flex flex-col gap-4 rounded-xl border border-slate-100 p-4 lg:flex-row lg:items-center"><div className="flex-1"><p className="font-semibold">{r[1]}</p><p className="mt-1 text-sm text-slate-500">{r[2]} · {r[3]}</p><p className="mt-1 text-xs text-slate-400">Request {r[0]}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${r[4]==='Pending'?'bg-amber-50 text-amber-700':r[4]==='Approved'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{r[4]}</span>{r[4]==='Pending'&&<div className="flex gap-2"><button onClick={()=>update(r[0],'Approved')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Approve</button><button onClick={()=>update(r[0],'Rejected')} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-600">Reject</button></div>}</div>)}</div></Panel></Shell>}
function ParentDashboard(){return <Shell title="Parent Dashboard" description="Welcome back. Here is Ahmed’s latest attendance summary."><Stats items={[["Attendance","92%",TrendingUp],["Present","30 days",Check],["Absences","2 days",X],["Late arrivals","1 day",Clock3]]}/><div className="grid gap-6 lg:grid-cols-2"><Panel title="Child profile"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-indigo-50 text-xl font-bold text-indigo-600">AK</div><div><h3 className="text-lg font-bold">Ahmed Khan</h3><p className="text-sm text-slate-500">Class 10-A · Roll No. 24</p><p className="mt-1 text-xs text-slate-400">Class teacher: Ayesha Malik</p></div></div></Panel><Panel title="This week"><div className="grid grid-cols-5 gap-2">{['M','T','W','T','F'].map((d,i)=><div key={`${d}${i}`} className="rounded-xl bg-slate-50 p-3 text-center"><p className="text-xs text-slate-400">{d}</p><div className={`mx-auto mt-2 grid h-8 w-8 place-items-center rounded-full ${i===3?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}><Check size={15}/></div></div>)}</div></Panel></div></Shell>}
function ParentAttendance(){return <Shell title="Attendance" description="Detailed attendance history for Ahmed Khan."><Panel><div className="mb-5 flex gap-3"><button className="rounded-xl border border-slate-200 px-4 py-2 text-sm">August 2026</button><button className="rounded-xl border border-slate-200 px-4 py-2 text-sm">All status</button></div><div className="space-y-2">{[['Aug 17','Monday','Present','08:02 AM'],['Aug 14','Friday','Late','08:21 AM'],['Aug 13','Thursday','Present','08:00 AM'],['Aug 12','Wednesday','Absent','—'],['Aug 11','Tuesday','Present','08:04 AM']].map(r=><div key={r[0]} className="flex items-center justify-between rounded-xl border border-slate-100 p-4"><div><p className="font-semibold">{r[1]}, {r[0]}</p><p className="text-xs text-slate-400">Check-in: {r[3]}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${r[2]==='Present'?'bg-emerald-50 text-emerald-700':r[2]==='Late'?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700'}`}>{r[2]}</span></div>)}</div></Panel></Shell>}
function ApplyLeave(){const [sent,setSent]=useState(false);return <Shell title="Apply for Leave" description="Submit a leave application to Ahmed’s class teacher."><Panel><div className="grid gap-5 sm:grid-cols-2"><Field label="Leave type"><select className="control"><option>Sick Leave</option><option>Personal Leave</option><option>Family Event</option><option>Medical Leave</option></select></Field><Field label="Start date"><input className="control" type="date"/></Field><Field label="End date"><input className="control" type="date"/></Field><Field label="Attachment (optional)"><input className="control" type="file"/></Field><div className="sm:col-span-2"><Field label="Reason"><textarea className="control min-h-32" placeholder="Please explain the reason for leave..."/></Field></div></div><div className="mt-6 flex justify-end"><button onClick={()=>setSent(true)} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">{sent?<><Check size={17}/> Application submitted</>:<><Send size={17}/> Submit application</>}</button></div></Panel></Shell>}
function LeaveHistory(){return <Shell title="Leave History" description="Track all leave applications submitted for your child."><Panel><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-4 py-3">Request</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Dates</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{[['LR-1042','Sick Leave','Aug 18 – Aug 19','Pending'],['LR-1030','Personal Leave','Aug 10','Approved'],['LR-1021','Family Event','Aug 3','Rejected']].map(r=><tr key={r[0]}><td className="px-4 py-4 font-semibold">{r[0]}</td><td className="px-4 py-4">{r[1]}</td><td className="px-4 py-4 text-slate-500">{r[2]}</td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${r[3]==='Pending'?'bg-amber-50 text-amber-700':r[3]==='Approved'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{r[3]}</span></td></tr>)}</tbody></table></div></Panel></Shell>}
function Shell({title,description,children}){return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-wider text-indigo-600">Attendance Management</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></header>{children}</div>}
function Panel({title,action,children}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between">{title&&<h3 className="font-bold text-slate-900">{title}</h3>}{action&&<button className="text-xs font-semibold text-indigo-600">{action} <ChevronRight size={14} className="inline"/></button>}</div>{children}</section>}
function Stats({items}){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon size={19}/></div></div></div>)}</div>}
function AttendanceTable({rows}){return <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">ID</th><th className="px-4 py-3">Check-in</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r[0]}><td className="px-4 py-4 font-semibold">{r[1]}</td><td className="px-4 py-4 text-slate-400">{r[0]}</td><td className="px-4 py-4 text-slate-500">{r[3]}</td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${r[2]==='Present'?'bg-emerald-50 text-emerald-700':r[2]==='Late'?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700'}`}>{r[2]}</span></td></tr>)}</tbody></table></div>}
function StatusButton({active,onClick,text,type}){const activeClass=type==='present'?'bg-emerald-600 text-white':type==='late'?'bg-amber-500 text-white':'bg-rose-600 text-white';return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-semibold ${active?activeClass:'border border-slate-200 text-slate-500 hover:bg-slate-50'}`}>{text}</button>}
function QuickAction({icon:Icon,title,text}){return <button className="flex w-full items-center gap-3 rounded-xl border border-slate-100 p-3 text-left hover:bg-slate-50"><div className="grid h-9 w-9 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><Icon size={17}/></div><div><p className="text-sm font-semibold">{title}</p><p className="text-xs text-slate-400">{text}</p></div></button>}
function Field({label,children}){return <label className="block space-y-2"><span className="block text-sm font-semibold text-slate-700">{label}</span>{children}</label>}
