import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronRight, Clock3, Download, FileText, Filter, Search, UserRound, Users, X, TrendingUp, Send, AlertCircle } from 'lucide-react'
import studentService from '../../services/studentService'
import classService from '../../services/classService'
import attendanceService from '../../services/attendanceService'
import leaveService from '../../services/leaveService'
import { getApiError } from '../../services/api'

const today = () => new Date().toISOString().slice(0, 10)
const statusLabel = (value) => value ? value[0].toUpperCase() + value.slice(1) : 'Unknown'

export default function PortalModule({ type }) {
  const pages = { teacherDashboard: <TeacherDashboard />, class: <MyClass />, monitoring: <AttendanceMonitoring />, history: <AttendanceHistory />, teacherLeaves: <TeacherLeaves />, parentDashboard: <ParentDashboard />, parentAttendance: <ParentAttendance />, applyLeave: <ApplyLeave />, leaveHistory: <LeaveHistory /> }
  return pages[type] || null
}

function useLoad(loader, deps = []) {
  const [state, setState] = useState({ loading: true, error: '', data: null })
  useEffect(() => { let active = true; setState({ loading: true, error: '', data: null }); loader().then((data) => active && setState({ loading: false, error: '', data })).catch((error) => active && setState({ loading: false, error: getApiError(error), data: null })); return () => { active = false } }, deps)
  return state
}

function TeacherDashboard() {
  const classes = useLoad(() => classService.list(), [])
  const students = useLoad(() => studentService.list({ limit: 100 }), [])
  const summary = useLoad(() => attendanceService.summary({ date: today() }), [])
  const stats = summary.data?.data || {}
  const total = students.data?.data?.length || 0
  return <Shell title="Teacher Dashboard" description="Live data from your attendance API."><Stats items={[["Students", total, Users], ["Present", stats.present || 0, Check], ["Late", stats.late || 0, Clock3], ["Absent", stats.absent || 0, X]]}/><div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><Panel title="My classes">{classes.loading ? <Loader/> : classes.error ? <ErrorBox text={classes.error}/> : <div className="space-y-3">{(classes.data?.data || []).map((item) => <div key={item._id} className="flex items-center justify-between rounded-xl border border-slate-100 p-4"><div><p className="font-semibold">{item.name} - {item.section}</p><p className="text-xs text-slate-400">{item.subject || item.grade || 'Class'} · {item.studentCount || 0} students</p></div><ChevronRight size={17} className="text-slate-300"/></div>)}</div>}</Panel><Panel title="Quick actions"><div className="space-y-3"><QuickAction icon={Check} title="Take attendance" text="Use Attendance Monitoring to save today’s status."/><QuickAction icon={FileText} title="Leave requests" text="Review pending parent applications."/><QuickAction icon={Download} title="History" text="View attendance records from the API."/></div></Panel></div></Shell>
}

function MyClass() {
  const [query, setQuery] = useState('')
  const state = useLoad(() => studentService.list({ limit: 100, search: query }), [query])
  const rows = state.data?.data || []
  return <Shell title="My Class" description="Students are loaded from your assigned class through the backend."><Panel><div className="flex flex-col gap-4 border-b border-slate-100 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold">Student roster</h3><p className="text-xs text-slate-400">{rows.length} students returned by the API.</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2"><Search size={17} className="text-slate-400"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search students..." className="w-52 bg-transparent text-sm outline-none"/></div></div>{state.loading ? <Loader/> : state.error ? <ErrorBox text={state.error}/> : <div className="mt-5"><StudentTable rows={rows}/></div>}</Panel></Shell>
}

function AttendanceMonitoring() {
  const state = useLoad(() => studentService.list({ limit: 100 }), [])
  const [rows, setRows] = useState([]); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { if (state.data?.data) setRows(state.data.data.map((student) => ({ ...student, status: 'present' }))) }, [state.data])
  const setStatus = (id, status) => setRows((items) => items.map((item) => item._id === id ? { ...item, status } : item))
  const save = async () => { setSaving(true); setError(''); setMessage(''); try { await attendanceService.bulk({ date: today(), records: rows.map((item) => ({ studentId: item._id, status: item.status })) }); setMessage('Attendance saved successfully.') } catch (requestError) { setError(getApiError(requestError)) } finally { setSaving(false) } }
  return <Shell title="Attendance Monitoring" description="Mark attendance and save it to MongoDB."><Panel><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold">{today()}</h3><p className="text-xs text-slate-400">Present, late and absent statuses are saved through the bulk API.</p></div><button disabled={saving || !rows.length} onClick={save} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save attendance'}</button></div>{message && <div className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{error && <ErrorBox text={error}/>} {state.loading ? <Loader/> : state.error ? <ErrorBox text={state.error}/> : <div className="space-y-3">{rows.map((s) => <div key={s._id} className="flex flex-col gap-3 rounded-xl border border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-indigo-50 text-indigo-600"><UserRound size={18}/></div><div><p className="font-semibold">{s.name}</p><p className="text-xs text-slate-400">{s.studentId} · {s.rollNumber || 'No roll'} · {s.class?.name || ''} {s.class?.section || ''}</p></div></div><div className="flex gap-2"><StatusButton active={s.status === 'present'} onClick={() => setStatus(s._id, 'present')} text="Present" type="present"/><StatusButton active={s.status === 'late'} onClick={() => setStatus(s._id, 'late')} text="Late" type="late"/><StatusButton active={s.status === 'absent'} onClick={() => setStatus(s._id, 'absent')} text="Absent" type="absent"/></div></div>)}</div>}</Panel></Shell>
}

function AttendanceHistory() {
  const state = useLoad(() => attendanceService.report({ from: new Date(Date.now() - 30 * 86400000).toISOString(), to: new Date().toISOString() }), [])
  return <Shell title="Attendance History" description="Last 30 days aggregated from the reporting API."><Panel><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2 text-sm text-slate-500"><CalendarDays size={16}/> Last 30 days</div><a href={attendanceService.exportUrl({})} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-3 py-2 text-sm font-semibold text-white"><Download size={16}/> Export</a></div>{state.loading ? <Loader/> : state.error ? <ErrorBox text={state.error}/> : <ReportTable rows={state.data?.data || []}/>}</Panel></Shell>
}

function TeacherLeaves() {
  const [refresh, setRefresh] = useState(0); const state = useLoad(() => leaveService.list({ status: 'pending' }), [refresh]); const [busy, setBusy] = useState(''); const [error, setError] = useState('')
  const update = async (id, status) => { setBusy(id); setError(''); try { await leaveService.updateStatus(id, { status }); setRefresh((v) => v + 1) } catch (requestError) { setError(getApiError(requestError)) } finally { setBusy('') } }
  return <Shell title="Leave Requests" description="Approve or reject requests stored in the backend."><Panel>{error && <ErrorBox text={error}/>} {state.loading ? <Loader/> : state.error ? <ErrorBox text={state.error}/> : <div className="space-y-3">{(state.data?.data || []).map((item) => <div key={item._id} className="flex flex-col gap-4 rounded-xl border border-slate-100 p-4 lg:flex-row lg:items-center"><div className="flex-1"><p className="font-semibold">{item.student?.name}</p><p className="mt-1 text-sm text-slate-500">{new Date(item.startDate).toLocaleDateString()} – {new Date(item.endDate).toLocaleDateString()} · {item.reason}</p><p className="mt-1 text-xs text-slate-400">Request {item._id.slice(-8)}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Pending</span><div className="flex gap-2"><button disabled={busy === item._id} onClick={() => update(item._id, 'approved')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Approve</button><button disabled={busy === item._id} onClick={() => update(item._id, 'rejected')} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-600">Reject</button></div></div>)}</div>}</Panel></Shell>
}

function ParentDashboard() {
  const students = useLoad(() => studentService.list({ limit: 20 }), []); const child = students.data?.data?.[0]; const history = useLoad(() => child ? attendanceService.studentHistory(child._id) : Promise.resolve({ data: [] }), [child?._id]); const total = history.data?.summary?.total || 0; const present = (history.data?.summary?.present || 0) + (history.data?.summary?.late || 0); const rate = total ? Math.round((present / total) * 100) : 0
  return <Shell title="Parent Dashboard" description="Your child’s attendance is now loaded from MongoDB.">{students.loading ? <Loader/> : students.error ? <ErrorBox text={students.error}/> : <><Stats items={[["Attendance", `${rate}%`, TrendingUp], ["Present", history.data?.summary?.present || 0, Check], ["Absences", history.data?.summary?.absent || 0, X], ["Late", history.data?.summary?.late || 0, Clock3]]}/><Panel title="Child profile"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-indigo-50 text-xl font-bold text-indigo-600">{child ? child.name.split(' ').map((x) => x[0]).slice(0, 2).join('') : 'ST'}</div><div><h3 className="text-lg font-bold">{child?.name || 'No student assigned'}</h3><p className="text-sm text-slate-500">{child?.class?.name || ''} {child?.class?.section || ''} · Roll {child?.rollNumber || '—'}</p><p className="mt-1 text-xs text-slate-400">{child?.studentId || ''}</p></div></div></Panel></>}</Shell>
}

function ParentAttendance() { const students = useLoad(() => studentService.list({ limit: 20 }), []); const child = students.data?.data?.[0]; const state = useLoad(() => child ? attendanceService.studentHistory(child._id) : Promise.resolve({ data: [] }), [child?._id]); return <Shell title="Attendance" description="Detailed history from the attendance API."><Panel>{state.loading || students.loading ? <Loader/> : state.error ? <ErrorBox text={state.error}/> : <div className="space-y-2">{(state.data?.data || []).map((item) => <div key={item._id} className="flex items-center justify-between rounded-xl border border-slate-100 p-4"><div><p className="font-semibold">{new Date(item.date).toLocaleDateString()}</p><p className="text-xs text-slate-400">Check-in: {item.checkInTime ? new Date(item.checkInTime).toLocaleTimeString() : '—'}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.status === 'present' ? 'bg-emerald-50 text-emerald-700' : item.status === 'late' ? 'bg-amber-50 text-amber-700' : 'bg-rose-50 text-rose-700'}`}>{statusLabel(item.status)}</span></div>)}</div>}</Panel></Shell> }

function ApplyLeave() { const students = useLoad(() => studentService.list({ limit: 20 }), []); const child = students.data?.data?.[0]; const [form, setForm] = useState({ startDate: today(), endDate: today(), reason: '' }); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { await leaveService.create({ studentId: child._id, ...form }); setSent(true); setForm({ startDate: today(), endDate: today(), reason: '' }) } catch (requestError) { setError(getApiError(requestError)) } finally { setSaving(false) } }; return <Shell title="Apply for Leave" description="Submit a leave application to the teacher."><Panel>{students.loading ? <Loader/> : !child ? <ErrorBox text="No child is linked to this parent account."/> : <form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field label="Student"><div className="control bg-slate-50">{child.name} · {child.studentId}</div></Field><Field label="Start date"><input required className="control" type="date" value={form.startDate} onChange={e => setForm({ ...form, startDate: e.target.value })}/></Field><Field label="End date"><input required className="control" type="date" value={form.endDate} onChange={e => setForm({ ...form, endDate: e.target.value })}/></Field><div className="sm:col-span-2"><Field label="Reason"><textarea required className="control min-h-32" value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} placeholder="Please explain the reason for leave..."/></Field></div>{error && <div className="sm:col-span-2"><ErrorBox text={error}/></div>}{sent && <div className="sm:col-span-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Leave application submitted successfully.</div>}<div className="sm:col-span-2 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Submitting…' : <><Send size={17}/> Submit application</>}</button></div></form>}</Panel></Shell> }

function LeaveHistory() { const state = useLoad(() => leaveService.list(), []); return <Shell title="Leave History" description="All leave applications for your child."><Panel>{state.loading ? <Loader/> : state.error ? <ErrorBox text={state.error}/> : <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-4 py-3">Request</th><th className="px-4 py-3">Student</th><th className="px-4 py-3">Dates</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{(state.data?.data || []).map((item) => <tr key={item._id}><td className="px-4 py-4 font-semibold">{item._id.slice(-8)}</td><td className="px-4 py-4">{item.student?.name}</td><td className="px-4 py-4 text-slate-500">{new Date(item.startDate).toLocaleDateString()} – {new Date(item.endDate).toLocaleDateString()}</td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.status === 'pending' ? 'bg-amber-50 text-amber-700' : item.status === 'approved' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{statusLabel(item.status)}</span></td></tr>)}</tbody></table></div>}</Panel></Shell> }

function Shell({ title, description, children }) { return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-wider text-indigo-600">Attendance Management</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></header>{children}</div> }
function Panel({ title, action, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{title && <div className="mb-5 flex items-center justify-between"><h3 className="font-bold text-slate-900">{title}</h3>{action && <button className="text-xs font-semibold text-indigo-600">{action} <ChevronRight size={14} className="inline"/></button>}</div>}{children}</section> }
function Stats({ items }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon size={19}/></div></div></div>)}</div> }
function StudentTable({ rows }) { return <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">ID</th><th className="px-4 py-3">Class</th><th className="px-4 py-3">Roll</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((item) => <tr key={item._id}><td className="px-4 py-4 font-semibold">{item.name}</td><td className="px-4 py-4 text-slate-500">{item.studentId}</td><td className="px-4 py-4 text-slate-500">{item.class?.name} {item.class?.section}</td><td className="px-4 py-4 text-slate-500">{item.rollNumber || '—'}</td></tr>)}</tbody></table></div> }
function ReportTable({ rows }) { return <div className="space-y-3">{rows.map((item) => <div key={item.status} className="flex items-center justify-between rounded-xl border border-slate-100 p-4"><span className="font-semibold">{statusLabel(item.status)}</span><span className="text-2xl font-bold">{item.count}</span></div>)}</div> }
function StatusButton({ active, onClick, text, type }) { const classes = active ? (type === 'present' ? 'bg-emerald-600 text-white' : type === 'late' ? 'bg-amber-500 text-white' : 'bg-rose-600 text-white') : 'border border-slate-200 text-slate-500 hover:bg-slate-50'; return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-semibold ${classes}`}>{text}</button> }
function QuickAction({ icon: Icon, title, text }) { return <div className="flex gap-3 rounded-xl border border-slate-100 p-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><Icon size={17}/></div><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-slate-400">{text}</p></div></div> }
function Field({ label, children }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label> }
function Loader() { return <div className="flex items-center justify-center py-12 text-sm text-slate-400">Loading data…</div> }
function ErrorBox({ text }) { return <div className="flex gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={18} className="shrink-0"/>{text}</div> }
