import { Camera, CheckCircle2, IdCard, RotateCcw, ScanLine, AlertCircle } from 'lucide-react'
import { useState } from 'react'
import kioskService from '../../services/kioskService'
import { getApiError } from '../../services/api'

export default function Scanner() {
  const [studentId, setStudentId] = useState('ST-001'); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const scan = async () => { setLoading(true); setError(''); try { const r = await kioskService.scan(studentId, 'present'); setResult(r.data) } catch (e) { setError(getApiError(e)) } finally { setLoading(false) } }
  return <div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-5xl items-center justify-center p-6"><div className="grid w-full gap-8 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">Scan student ID</h2><p className="mt-1 text-sm text-slate-400">QR SDK can call the same endpoint when added.</p></div><Camera className="text-indigo-400"/></div><div className="mt-8 grid aspect-square place-items-center rounded-3xl border-2 border-dashed border-indigo-400/50 bg-slate-900"><div className="relative grid h-64 w-64 place-items-center rounded-2xl border border-indigo-400/50"><ScanLine size={170} className="text-indigo-400"/><span className="absolute bottom-4 rounded-full bg-black/50 px-3 py-1 text-xs text-slate-300">Ready</span></div></div><div className="mt-6 flex gap-2"><input value={studentId} onChange={e => setStudentId(e.target.value)} className="w-full rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm text-white outline-none" placeholder="Student ID e.g. ST-001"/><button disabled={loading} onClick={scan} className="shrink-0 rounded-xl bg-indigo-500 px-5 py-3 font-semibold hover:bg-indigo-400 disabled:opacity-50">{loading ? 'Scanning…' : 'Scan'}</button></div>{error && <div className="mt-4 flex gap-2 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-300"><AlertCircle size={18}/>{error}</div>}</section><section className="flex flex-col justify-center rounded-3xl border border-white/10 bg-white/5 p-8">{result ? <><div className="grid h-16 w-16 place-items-center rounded-2xl bg-emerald-500/10 text-emerald-400"><CheckCircle2 size={32}/></div><p className="mt-6 text-sm font-semibold uppercase tracking-wider text-emerald-400">Attendance recorded</p><h3 className="mt-2 text-3xl font-bold">{result.student?.name}</h3><p className="mt-2 text-slate-400">{result.class?.name} {result.class?.section} · Roll No. {result.student?.rollNumber || '—'}</p><div className="mt-8 grid grid-cols-2 gap-3"><Info icon={IdCard} label="Student ID" value={result.student?.studentId}/><Info icon={ScanLine} label="Check-in" value={result.checkInTime ? new Date(result.checkInTime).toLocaleTimeString() : '—'}/></div><button onClick={() => setResult(null)} className="mt-8 inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm font-semibold text-slate-300"><RotateCcw size={16}/> Scan another</button></> : <div><div className="grid h-16 w-16 place-items-center rounded-2xl bg-indigo-500/10 text-indigo-400"><ScanLine size={30}/></div><h3 className="mt-6 text-2xl font-bold">Ready to scan</h3><p className="mt-2 leading-7 text-slate-400">Use a real QR/barcode scanner later or enter a seeded student ID to test the live kiosk API now.</p></div>}</section></div></div>
}
function Info({ icon: Icon, label, value }) { return <div className="rounded-xl bg-white/5 p-4"><Icon size={18} className="text-slate-400"/><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div> }
