import { useEffect, useState } from 'react'
import { CalendarDays, RefreshCw, Check, X, Clock3, AlertCircle } from 'lucide-react'
import attendanceService from '../../services/attendanceService'
import { getApiError } from '../../services/api'

export default function Attendance() {
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [rows, setRows] = useState([]); const [summary, setSummary] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const [a, b] = await Promise.all([attendanceService.list({ date }), attendanceService.summary({ date })]); setRows(a.data || []); setSummary(b.data || {}) } catch (e) { setError(getApiError(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [date])
  const mark = async (studentId, status) => { try { await attendanceService.mark({ studentId, status, date, source: 'manual' }); load() } catch (e) { setError(getApiError(e)) } }
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold">Attendance</h2><p className="mt-1 text-sm text-slate-500">View and manually update daily attendance records.</p></div><div className="flex items-center gap-2"><CalendarDays size={17} className="text-slate-400"/><input type="date" value={date} onChange={e => setDate(e.target.value)} className="control w-auto"/><button onClick={load} className="rounded-xl border border-slate-200 p-2.5"><RefreshCw size={17}/></button></div></div>{error && <div className="flex gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={18}/>{error}</div>}<div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Stat label="Present" value={summary.present || 0} icon={Check}/><Stat label="Absent" value={summary.absent || 0} icon={X}/><Stat label="Late" value={summary.late || 0} icon={Clock3}/><Stat label="Excused" value={summary.excused || 0} icon={Check}/></div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h3 className="font-bold">Saved records</h3><p className="mt-1 text-xs text-slate-400">{loading ? 'Loading…' : `${rows.length} attendance records for ${date}`}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Class</th><th className="px-5 py-3">Check-in</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Change</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(item => <tr key={item._id}><td className="px-5 py-4 font-semibold">{item.student?.name}<span className="ml-2 text-xs font-normal text-slate-400">{item.student?.studentId}</span></td><td className="px-5 py-4 text-slate-500">{item.class?.name} {item.class?.section}</td><td className="px-5 py-4 text-slate-500">{item.checkInTime ? new Date(item.checkInTime).toLocaleTimeString() : '—'}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{item.status}</span></td><td className="px-5 py-4"><div className="flex gap-1"><button onClick={() => mark(item.student?._id, 'present')} className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">Present</button><button onClick={() => mark(item.student?._id, 'late')} className="rounded-lg bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700">Late</button><button onClick={() => mark(item.student?._id, 'absent')} className="rounded-lg bg-rose-50 px-2 py-1 text-xs font-semibold text-rose-700">Absent</button></div></td></tr>)}{!loading && !rows.length && <tr><td colSpan="5" className="px-5 py-12 text-center text-slate-400">No attendance records for this date.</td></tr>}</tbody></table></div></section></div>
}
function Stat({ label, value, icon: Icon }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div><Icon size={19} className="text-indigo-500"/></div></div> }
