import { useEffect, useState } from 'react'
import { Check, X, RefreshCw, AlertCircle } from 'lucide-react'
import leaveService from '../../services/leaveService'
import { getApiError } from '../../services/api'

export default function LeaveRequests() {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState('pending'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const r = await leaveService.list(filter === 'all' ? {} : { status: filter }); setItems(r.data || []) } catch (e) { setError(getApiError(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [filter])
  const update = async (id, status) => { setBusy(id); setError(''); try { await leaveService.updateStatus(id, { status }); load() } catch (e) { setError(getApiError(e)) } finally { setBusy('') } }
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold">Leave Requests</h2><p className="mt-1 text-sm text-slate-500">Approve or reject parent applications.</p></div><div className="flex gap-2"><select value={filter} onChange={e => setFilter(e.target.value)} className="control w-auto"><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="all">All</option></select><button onClick={load} className="rounded-xl border border-slate-200 p-2.5"><RefreshCw size={17}/></button></div></div>{error && <ErrorBox text={error}/>}<section className="space-y-3">{loading ? <div className="py-12 text-center text-slate-400">Loading requests…</div> : items.map(item => <div key={item._id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="flex-1"><div className="flex items-center gap-3"><h3 className="font-bold">{item.student?.name || 'Student'}</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{item.status}</span></div><p className="mt-2 text-sm text-slate-500">{new Date(item.startDate).toLocaleDateString()} – {new Date(item.endDate).toLocaleDateString()}</p><p className="mt-2 text-sm">{item.reason}</p><p className="mt-2 text-xs text-slate-400">Parent: {item.parent?.name || '—'} · {item.parent?.phone || item.parent?.email || '—'}</p></div>{item.status === 'pending' && <div className="flex gap-2"><button disabled={busy === item._id} onClick={() => update(item._id, 'approved')} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white"><Check size={15}/> Approve</button><button disabled={busy === item._id} onClick={() => update(item._id, 'rejected')} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-600"><X size={15}/> Reject</button></div>}</div></div>)}{!loading && !items.length && <div className="rounded-2xl border border-dashed border-slate-300 py-12 text-center text-slate-400">No {filter === 'all' ? '' : filter} requests.</div>}</section></div>
}
function ErrorBox({ text }) { return <div className="flex gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={18}/>{text}</div> }
