import { useEffect, useState } from 'react'
import { Bell, CheckCheck, Send, AlertCircle } from 'lucide-react'
import notificationService from '../../services/notificationService'
import { getApiError } from '../../services/api'

export default function Notifications() {
  const [items, setItems] = useState([]); const [form, setForm] = useState({ title: '', message: '', role: '' }); const [error, setError] = useState(''); const [sent, setSent] = useState('')
  const load = async () => { try { const r = await notificationService.list(); setItems(r.data || []) } catch (e) { setError(getApiError(e)) } }
  useEffect(() => { load() }, [])
  const readAll = async () => { try { await notificationService.markAllRead(); load() } catch (e) { setError(getApiError(e)) } }
  const send = async (e) => { e.preventDefault(); setError(''); setSent(''); try { const r = await notificationService.broadcast(form); setSent(`Notification sent to ${r.sent} users.`); setForm({ title: '', message: '', role: '' }) } catch (e2) { setError(getApiError(e2)) } }
  return <div className="mx-auto max-w-5xl space-y-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">Notifications</h2><p className="mt-1 text-sm text-slate-500">Read alerts and broadcast school announcements.</p></div><button onClick={readAll} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold"><CheckCheck size={16}/> Mark all read</button></div>{error && <ErrorBox text={error}/>}<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">Send announcement</h3><form onSubmit={send} className="mt-5 grid gap-4 sm:grid-cols-2"><input required className="control" placeholder="Title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/><select className="control" value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option value="">Everyone</option><option value="teacher">Teachers</option><option value="parent">Parents</option><option value="admin">Admins</option></select><textarea required className="control min-h-28 sm:col-span-2" placeholder="Message" value={form.message} onChange={e => setForm({ ...form, message: e.target.value })}/><div className="sm:col-span-2 flex items-center justify-between">{sent ? <span className="text-sm text-emerald-600">{sent}</span> : <span/>}<button className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><Send size={16}/> Send</button></div></form></section><section className="space-y-3">{items.map(item => <div key={item._id} className={`flex gap-4 rounded-2xl border p-5 ${item.readAt ? 'border-slate-200 bg-white' : 'border-indigo-100 bg-indigo-50/40'}`}><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-indigo-100 text-indigo-600"><Bell size={18}/></div><div className="flex-1"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-500">{item.message}</p><p className="mt-2 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</p></div></div>)}{!items.length && <div className="py-12 text-center text-slate-400">No notifications yet.</div>}</section></div>
}
function ErrorBox({ text }) { return <div className="flex gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={18}/>{text}</div> }
