import { useEffect, useState } from 'react'
import { Download, BarChart3, AlertCircle, RefreshCw } from 'lucide-react'
import reportService from '../../services/reportService'
import { getApiError } from '../../services/api'

export default function Reports() {
  const [data, setData] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async () => { setLoading(true); try { const r = await reportService.attendance({}); setData(r.data || []) } catch (e) { setError(getApiError(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const download = async () => { try { const blob = await reportService.exportAttendance({}); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'attendance-report.csv'; a.click(); URL.revokeObjectURL(url) } catch (e) { setError(getApiError(e)) } }
  const total = data.reduce((sum, x) => sum + x.count, 0)
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold">Reports</h2><p className="mt-1 text-sm text-slate-500">Attendance analytics from the backend aggregation API.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-slate-200 p-2.5"><RefreshCw size={17}/></button><button onClick={download} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><Download size={17}/> Export CSV</button></div></div>{error && <div className="flex gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={18}/>{error}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{['present','absent','late','excused'].map(status => <div key={status} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm capitalize text-slate-500">{status}</p><p className="mt-1 text-3xl font-bold">{data.find(x => x.status === status)?.count || 0}</p></div>)}</div><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><BarChart3 size={19}/></div><div><h3 className="font-bold">Attendance distribution</h3><p className="text-xs text-slate-400">Total records in the default reporting window: {total}</p></div></div>{loading ? <p className="py-12 text-center text-slate-400">Loading report…</p> : <div className="mt-7 space-y-4">{data.map(item => <div key={item.status}><div className="mb-1 flex justify-between text-sm"><span className="capitalize font-semibold">{item.status}</span><span>{total ? Math.round(item.count / total * 100) : 0}%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${total ? item.count / total * 100 : 0}%` }}/></div></div>)}</div>}</section></div>
}
