import { useEffect, useState } from 'react'
import { Save, Settings as SettingsIcon, AlertCircle, CheckCircle2 } from 'lucide-react'
import settingsService from '../../services/settingsService'
import { getApiError } from '../../services/api'

export default function Settings() {
  const [form, setForm] = useState({ schoolName: '', email: '', phone: '', address: '', attendanceCutoff: '08:30', lateAfterMinutes: 15, timezone: 'Asia/Karachi', whatsappEnabled: false }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
  useEffect(() => { settingsService.get().then(r => setForm({ ...form, ...r.data })).catch(e => setError(getApiError(e))).finally(() => setLoading(false)) }, [])
  const change = (key, value) => setForm(x => ({ ...x, [key]: value }))
  const submit = async e => { e.preventDefault(); setSaving(true); setError(''); setSaved(false); try { const r = await settingsService.update(form); setForm(r.data); setSaved(true) } catch (e2) { setError(getApiError(e2)) } finally { setSaving(false) } }
  return <div className="mx-auto max-w-4xl space-y-6"><div><h2 className="text-2xl font-bold">Settings</h2><p className="mt-1 text-sm text-slate-500">School settings stored in MongoDB.</p></div>{error && <div className="flex gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={18}/>{error}</div>}<form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><SettingsIcon size={19}/></div><div><h3 className="font-bold">School configuration</h3><p className="text-xs text-slate-400">These values are returned by the settings API.</p></div></div>{loading ? <div className="py-12 text-center text-slate-400">Loading settings…</div> : <><div className="mt-6 grid gap-5 md:grid-cols-2"><Field label="School name"><input className="control" value={form.schoolName} onChange={e => change('schoolName', e.target.value)}/></Field><Field label="Email"><input className="control" type="email" value={form.email} onChange={e => change('email', e.target.value)}/></Field><Field label="Phone"><input className="control" value={form.phone} onChange={e => change('phone', e.target.value)}/></Field><Field label="Attendance cutoff"><input className="control" type="time" value={form.attendanceCutoff} onChange={e => change('attendanceCutoff', e.target.value)}/></Field><Field label="Late after minutes"><input className="control" type="number" min="0" value={form.lateAfterMinutes} onChange={e => change('lateAfterMinutes', Number(e.target.value))}/></Field><Field label="Timezone"><input className="control" value={form.timezone} onChange={e => change('timezone', e.target.value)}/></Field><Field label="Address"><textarea className="control min-h-24" value={form.address} onChange={e => change('address', e.target.value)}/></Field><label className="flex items-center gap-3 pt-7 text-sm font-semibold"><input type="checkbox" checked={Boolean(form.whatsappEnabled)} onChange={e => change('whatsappEnabled', e.target.checked)}/> Enable WhatsApp integration flag</label></div><div className="mt-6 flex justify-end gap-3">{saved && <span className="inline-flex items-center gap-2 text-sm text-emerald-600"><CheckCircle2 size={16}/> Saved</span>}<button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50"><Save size={17}/>{saving ? 'Saving…' : 'Save settings'}</button></div></>}</form></div>
}
function Field({ label, children }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label> }
