import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, CreditCard, UserRound, CalendarDays, AlertCircle } from 'lucide-react'
import studentService from '../../services/studentService'
import attendanceService from '../../services/attendanceService'
import { getApiError } from '../../services/api'

export default function StudentProfile() {
  const { id } = useParams(); const [student, setStudent] = useState(null); const [history, setHistory] = useState(null); const [error, setError] = useState('')
  useEffect(() => { Promise.all([studentService.get(id), attendanceService.studentHistory(id)]).then(([a, b]) => { setStudent(a.data); setHistory(b) }).catch(e => setError(getApiError(e))) }, [id])
  if (error) return <div className="mx-auto max-w-4xl"><ErrorBox text={error}/></div>
  if (!student) return <div className="py-16 text-center text-slate-400">Loading student…</div>
  return <div className="mx-auto max-w-5xl space-y-6"><div className="flex items-center gap-3"><Link to="/admin/students" className="rounded-xl border border-slate-200 p-2.5 text-slate-500"><ArrowLeft size={18}/></Link><div><h2 className="text-2xl font-bold">{student.name}</h2><p className="mt-1 text-sm text-slate-500">{student.studentId} · {student.class?.name} {student.class?.section}</p></div></div><div className="grid gap-6 lg:grid-cols-[1fr_1.4fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><UserRound size={25}/></div><div><h3 className="text-lg font-bold">Student details</h3><p className="text-sm text-slate-500">Roll: {student.rollNumber || '—'}</p></div></div><dl className="mt-6 space-y-4 text-sm"><Row label="Father name" value={student.fatherName}/><Row label="WhatsApp" value={student.whatsapp || '—'}/><Row label="Email" value={student.email || '—'}/><Row label="Parent" value={student.parent?.name || '—'}/><Row label="Parent phone" value={student.parent?.phone || '—'}/><Row label="Class" value={`${student.class?.name || ''} ${student.class?.section || ''}`}/></dl><Link to={`/admin/students/${id}/card`} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><CreditCard size={17}/> View ID card</Link></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-bold">Attendance summary</h3><p className="text-xs text-slate-400">Last 365 attendance records</p></div><CalendarDays size={20} className="text-indigo-500"/></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Total" value={history?.summary?.total || 0}/><Stat label="Present" value={history?.summary?.present || 0}/><Stat label="Absent" value={history?.summary?.absent || 0}/><Stat label="Late" value={history?.summary?.late || 0}/></div><div className="mt-6 space-y-2">{(history?.data || []).slice(0, 10).map(item => <div key={item._id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{new Date(item.date).toLocaleDateString()}</span><span className="font-semibold">{item.status}</span></div>)}</div></section></div></div>
}
function Row({ label, value }) { return <div className="flex justify-between gap-4 border-b border-slate-100 pb-3"><dt className="text-slate-400">{label}</dt><dd className="text-right font-semibold">{value}</dd></div> }
function Stat({ label, value }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div> }
function ErrorBox({ text }) { return <div className="flex gap-2 rounded-xl bg-rose-50 p-4 text-sm text-rose-700"><AlertCircle size={18}/>{text}</div> }
