import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, CreditCard, Printer, QrCode, AlertCircle } from 'lucide-react'
import studentService from '../../services/studentService'
import { getApiError } from '../../services/api'

export default function StudentIDCard() {
  const { id } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { studentService.idCard(id).then(r => setData(r.data)).catch(e => setError(getApiError(e))) }, [id])
  if (error) return <ErrorBox text={error}/>
  if (!data) return <div className="py-16 text-center text-slate-400">Loading ID card…</div>
  const s = data.student
  return <div className="mx-auto max-w-3xl space-y-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Link to={`/admin/students/${id}`} className="rounded-xl border border-slate-200 p-2.5 text-slate-500"><ArrowLeft size={18}/></Link><div><h2 className="text-2xl font-bold">Student ID Card</h2><p className="text-sm text-slate-500">Generated from the student record.</p></div></div><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><Printer size={17}/> Print</button></div><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><div className="bg-indigo-600 p-6 text-white"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white text-indigo-600"><CreditCard size={22}/></div><div><p className="text-lg font-bold">Attendly School</p><p className="text-xs text-indigo-100">Student identification card</p></div></div></div><div className="grid gap-8 p-8 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="grid h-24 w-24 place-items-center rounded-2xl bg-indigo-50 text-3xl font-bold text-indigo-600">{s.name.split(' ').map(x => x[0]).slice(0,2).join('')}</div><h3 className="mt-5 text-2xl font-bold">{s.name}</h3><p className="mt-1 font-semibold text-indigo-600">{s.studentId}</p><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-8"><dt className="text-slate-400">Father</dt><dd className="font-semibold">{s.fatherName}</dd></div><div className="flex justify-between gap-8"><dt className="text-slate-400">Class</dt><dd className="font-semibold">{s.class?.name} {s.class?.section}</dd></div><div className="flex justify-between gap-8"><dt className="text-slate-400">Roll No.</dt><dd className="font-semibold">{s.rollNumber || '—'}</dd></div><div className="flex justify-between gap-8"><dt className="text-slate-400">WhatsApp</dt><dd className="font-semibold">{s.whatsapp || '—'}</dd></div></dl></div><div className="rounded-2xl border border-slate-200 p-5 text-center"><QrCode size={120} className="mx-auto text-slate-800"/><p className="mt-3 text-xs font-mono text-slate-500">{data.qrValue}</p></div></div></section></div>
}
function ErrorBox({ text }) { return <div className="mx-auto max-w-3xl flex gap-2 rounded-xl bg-rose-50 p-4 text-sm text-rose-700"><AlertCircle size={18}/>{text}</div> }
