import { ArrowLeft, CalendarDays, Mail, Phone, MapPin, GraduationCap, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Badge from '../../components/ui/Badge'

export default function StudentProfile() {
  const { id } = useParams()
  return <div className="mx-auto max-w-6xl space-y-6">
    <div className="flex items-center gap-3"><Link to="/admin/students" className="rounded-xl border border-slate-200 p-2.5 text-slate-500 hover:bg-slate-50"><ArrowLeft size={18}/></Link><div><p className="text-xs font-semibold uppercase tracking-wider text-indigo-600">Student profile</p><h2 className="text-2xl font-bold text-slate-900">Ahmed Khan</h2></div></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="h-28 bg-gradient-to-r from-indigo-600 via-indigo-500 to-violet-500"/><div className="px-6 pb-6"><div className="-mt-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-4"><div className="grid h-20 w-20 place-items-center rounded-2xl border-4 border-white bg-indigo-50 text-indigo-600 shadow"><UserRound size={32}/></div><div><h3 className="text-xl font-bold">Ahmed Khan</h3><p className="text-sm text-slate-500">Student ID: {id || 'ST-1001'} · Class 10-A</p></div></div><Badge status="present">Present today</Badge></div></div></section>
    <div className="grid gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><h3 className="font-bold">Personal information</h3><div className="mt-5 grid gap-5 sm:grid-cols-2"><Info icon={CalendarDays} label="Date of birth" value="15 March 2010"/><Info icon={GraduationCap} label="Gender" value="Male"/><Info icon={Mail} label="Email" value="ahmed.khan@school.com"/><Info icon={Phone} label="Phone" value="+92 300 1234567"/><Info icon={MapPin} label="Address" value="Gulshan-e-Iqbal, Karachi"/></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">Attendance overview</h3><div className="mt-5 space-y-4"><Stat label="Present" value="92%"/><Stat label="Late" value="5%"/><Stat label="Absent" value="3%"/></div></section></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">Recent attendance</h3><div className="mt-4 divide-y divide-slate-100">{[['Monday, Aug 17','08:02 AM','Present'],['Friday, Aug 14','08:18 AM','Late'],['Thursday, Aug 13','08:00 AM','Present'],['Wednesday, Aug 12','—','Absent']].map(([date,time,status]) => <div key={date} className="flex items-center justify-between py-4"><div><p className="font-medium">{date}</p><p className="text-xs text-slate-400">Check-in: {time}</p></div><Badge status={status.toLowerCase()}>{status}</Badge></div>)}</div></section>
  </div>
}
function Info({ icon: Icon, label, value }) { return <div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-50 text-slate-500"><Icon size={17}/></div><div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-sm font-medium text-slate-700">{value}</p></div></div> }
function Stat({ label, value }) { return <div className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="text-sm text-slate-500">{label}</span><span className="font-bold text-slate-800">{value}</span></div> }
