import { useEffect, useState } from 'react'
import { Plus, UserRound, Trash2, RefreshCw, AlertCircle } from 'lucide-react'
import teacherService from '../../services/teacherService'
import { getApiError } from '../../services/api'

const blank = { employeeId: '', name: '', email: '', phone: '', subject: '', qualification: '' }
export default function Teachers() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const load = async () => { setLoading(true); try { const r = await teacherService.list(); setItems(r.data || []) } catch (e) { setError(getApiError(e)) } finally { setLoading(false) } }; useEffect(() => { load() }, [])
  const create = async e => { e.preventDefault(); setSaving(true); setError(''); try { await teacherService.create(form); setForm(blank); setOpen(false); load() } catch (e2) { setError(getApiError(e2)) } finally { setSaving(false) } }
  const remove = async id => { if (!window.confirm('Deactivate this teacher?')) return; try { await teacherService.remove(id); load() } catch (e) { setError(getApiError(e)) } }
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold">Teachers</h2><p className="mt-1 text-sm text-slate-500">Manage teacher accounts and profiles.</p></div><button onClick={() => setOpen(v => !v)} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/> Add teacher</button></div>{error && <div className="flex gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={18}/>{error}</div>}{open && <form onSubmit={create} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2">{[['employeeId','Employee ID'],['name','Full name'],['email','Email'],['phone','Phone'],['subject','Subject'],['qualification','Qualification']].map(([key,label]) => <input key={key} required={['employeeId','name','email'].includes(key)} className="control" placeholder={label} type={key === 'email' ? 'email' : 'text'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/>)}<div className="md:col-span-2 flex justify-end"><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white">{saving ? 'Saving…' : 'Create teacher'}</button></div></form>}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><h3 className="font-bold">Teacher directory</h3><button onClick={load} className="rounded-lg p-2 text-slate-400"><RefreshCw size={17}/></button></div><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-5 py-3">Teacher</th><th className="px-5 py-3">Employee ID</th><th className="px-5 py-3">Subject</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan="5" className="p-10 text-center text-slate-400">Loading…</td></tr> : items.map(item => <tr key={item._id}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-indigo-50 text-indigo-600"><UserRound size={17}/></div><div><p className="font-semibold">{item.name}</p><p className="text-xs text-slate-400">{item.email}</p></div></div></td><td className="px-5 py-4 text-slate-500">{item.employeeId}</td><td className="px-5 py-4 text-slate-500">{item.subject || '—'}</td><td className="px-5 py-4 text-slate-500">{item.phone || '—'}</td><td className="px-5 py-4"><button onClick={() => remove(item._id)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={17}/></button></td></tr>)}</tbody></table></div></section></div>
}
